name 'lamp_jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures lamp_jenkins'
long_description 'Installs/Configures lamp_jenkins'
version '0.1.0'

depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.3.5'
depends 'mysql', '~> 7.0.0'
depends 'ssl_certificate', '~> 1.11.0'
depends 'selinux_policy', '~> 0.9.5'
